In [47]:
import numpy as np
from sklearn.linear_model import LinearRegression

x = np.arange(10).reshape(-1, 1)
y = (2*x + 1).reshape(-1, 1)

# 모델 선언
model = LinearRegression()

# 학습
model.fit(x, y) # x에 데이터, y에 예측값

# 예측
prediction = model.predict([[10.0]]) #x에 10을 넣었을 때 예측값은 얼마?
prediction


array([[21.]])

In [38]:
import numpy as np
import pandas as pd
train = pd.read_csv('train_titanic.csv')
train.head()

PassengerId: 승객 아이디
Survived: 생존 여부, 1: 생존, 0: 사망
Pclass: 등급
Name: 성함
Sex: 성별
Age: 나이
SibSp: 형제, 자매, 배우자 수
Parch: 부모, 자식 수
Ticket: 티켓번호
Fare: 요즘
Cabin: 좌석번호
Embarked: 탑승 항구

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [40]:
feature = [
    'Pclass', 'Sex', 'Age', 'Fare'
]

label = [
    'Survived'
]

In [42]:
train[feature].head()

Pclass     Sex   Age     Fare
0       3    male  22.0   7.2500
1       1  female  38.0  71.2833
2       3  female  26.0   7.9250
3       1  female  35.0  53.1000
4       3    male  35.0   8.0500

In [43]:
train[label].head()

Survived
0         0
1         1
2         1
3         1
4         0

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(train[feature], train[label], test_size=0.2, shuffle=True, random_state=30)
#리턴 순서가 중요함!!

In [45]:
x_train.shape, y_train.shape

((712, 4), (712, 1))

In [46]:
x_valid.shape, y_valid.shape

((179, 4), (179, 1))

In [50]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [68]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

결측치 0으로 채우기

In [53]:
train['Age'].fillna(0).describe()

count    891.000000
mean      23.799293
std       17.596074
min        0.000000
25%        6.000000
50%       24.000000
75%       35.000000
max       80.000000
Name: Age, dtype: float64

이번엔 평균값으로 채우기

In [62]:
train['Age'].fillna(train['Age'].mean()).describe()

count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64

imputer는 결측치를 처리하는 함수

fit() 을 통해 결측치에 대한 학습을 진행합니다.

transform() 은 실제 결측치에 대한 처리를 해주는 함수합니다.

In [63]:
from sklearn.impute import SimpleImputer

# 결측치를 mean으로 처리한다.
imputer = SimpleImputer(strategy='mean')
# fit으로 결측치를 학습
imputer.fit(train[['Age', 'Pclass']])
# transform으로 결측치 처리
result = imputer.transform(train[['Age', 'Pclass']])
result

array([[22.        ,  3.        ],
       [38.        ,  1.        ],
       [26.        ,  3.        ],
       ...,
       [29.69911765,  3.        ],
       [26.        ,  1.        ],
       [32.        ,  3.        ]])

In [67]:
train[['Age', 'Pclass']] = imputer.transform(train[['Age', 'Pclass']])
# 결측치가 제거 된 값을 다시 할당

In [71]:
train[['Age', 'Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

위의 결과를 한번에 처리하는 법

imputer.fit_transform

In [117]:
train = pd.read_csv('train_titanic.csv')

# 이번엔 메디안으로 해봄
imputer = SimpleImputer(strategy='median')

train[['Age', 'Pclass']] = imputer.fit_transform(train[['Age', 'Pclass']])

train[['Age', 'Pclass']].isnull().sum()

Age       0
Pclass    0
dtype: int64

In [74]:
train[['Age', 'Pclass']].describe()

Age      Pclass
count  891.000000  891.000000
mean    29.361582    2.308642
std     13.019697    0.836071
min      0.420000    1.000000
25%     22.000000    2.000000
50%     28.000000    3.000000
75%     35.000000    3.000000
max     80.000000    3.000000

그럼 범주형은? Categorical

In [77]:
train[['Embarked', 'Cabin']].isnull().sum()

Embarked      2
Cabin       687
dtype: int64

In [118]:
#train['Embarked'].fillna('S')

#가장 많이 나온걸로 채워
imputer = SimpleImputer(strategy='most_frequent')

train[['Embarked', 'Cabin']] = imputer.fit_transform(train[['Embarked', 'Cabin']])

train[['Embarked', 'Cabin']].isnull().sum()

Embarked    0
Cabin       0
dtype: int64

Label Encoding : 문자(categorical)를 수치(numerical)로 변환

학습을 위해서 모든 문자로된 데이터는 수치로 변환하여야 합니다.

In [99]:
train.info()
train[feature + label].head()
# 현재 sex가 문자여서 안됨 이거 바꿔주자

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    float64
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(3), int64(4), object(5)
memory usage: 83.7+ KB


Pclass     Sex   Age     Fare  Survived
0     3.0    male  22.0   7.2500         0
1     1.0  female  38.0  71.2833         1
2     3.0  female  26.0   7.9250         1
3     1.0  female  35.0  53.1000         1
4     3.0    male  35.0   8.0500         0

In [100]:
def convert(data):
    if data == 'male':
        return 1
    elif data == 'female':
        return 0

In [103]:
train['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [114]:
train['Sex'] = train['Sex'].apply(convert)
train['Sex']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex, Length: 891, dtype: int64

마찬가지로 위의 과정을 한번에

In [119]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [123]:
#자동으로 변환?
train['Sex_num'] = le.fit_transform(train['Sex'])
train['Sex_num']

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: Sex_num, Length: 891, dtype: int32

In [121]:
train['Sex_num'].value_counts()

1    577
0    314
Name: Sex_num, dtype: int64

In [122]:
le.classes_

array(['female', 'male'], dtype=object)

In [ ]:
le.inverse_transform(train['Sex_num'])
# 되돌리기 쌉가능
# NaN값 있으면 오류 뱉음

원 핫 인코딩 (One Hot Encoding)

더미(dummy)변수 생성

In [126]:
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [127]:
train['Embarked'] = train['Embarked'].fillna('S')
train['Embarked'].value_counts()

S    646
C    168
Q     77
Name: Embarked, dtype: int64

In [128]:
train['Embarked_num'] = LabelEncoder().fit_transform(train['Embarked'])
train['Embarked_num'].value_counts()

2    646
0    168
1     77
Name: Embarked_num, dtype: int64

Embarked는 탑승 항구의 이니셜을 나타냈습니다.

그런데, 우리는 이전에 배운 내용처럼 LabelEncoder를 통해서 수치형으로 변환해주었습니다.

하지만, 이대로 데이터를 기계학습을 시키면, 기계는 데이터 안에서 관계를 학습합니다.

즉, 'S' = 2, 'Q' = 1 이라고 되어 있는데, Q + Q = S 가 된다 라고 학습해버린다는 것이죠.

그렇기 때문에, 독립적인 데이터는 별도의 column으로 분리하고, 각각의 컬럼에 해당 값에만 True 나머지는 False를 갖습니다. 우리는 이것은 원 핫 인코딩 한다라고 합니다.

In [131]:
one_hot = pd.get_dummies(train['Embarked'][:6])
one_hot

C  Q  S
0  0  0  1
1  1  0  0
2  0  0  1
3  0  0  1
4  0  0  1
5  0  1  0

위와 같이 column 을 분리시켜 카테고리형 -> 수치형으로 변환하면서 생기는 수치형 값의 관계를 끊어주어서 독립적인 형태로 바꾸어 줍니다.

원핫인코딩은 카테고리 (계절, 항구, 성별, 종류, 한식/일식/중식...)의 특성을 가지는 column에 대해서 적용 합니다.

전처리: Normalize (정규화)

column 간에 다른 min, max 값을 가지는 경우, 정규화를 통해 



최소치/ 최대값의 척도를 맞추어 주는 것

네이버 영화평점 (0점 ~ 10점): [2, 4, 6, 8, 10]

넷플릭스 영화평점 (0점 ~ 5점): [1, 2, 3, 4, 5]

In [132]:
movie = {'naver': [2, 4, 6, 8, 10], 
         'netflix': [1, 2, 3, 4, 5]
         }

movie = pd.DataFrame(data=movie)
movie

naver  netflix
0      2        1
1      4        2
2      6        3
3      8        4
4     10        5

In [133]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

In [138]:
min_max_movie = min_max_scaler.fit_transform(movie)

pd.DataFrame(min_max_movie, columns=['naver', 'netflix'])

naver  netflix
0   0.00     0.00
1   0.25     0.25
2   0.50     0.50
3   0.75     0.75
4   1.00     1.00

표준화 (Standard Scaling)

평균이 0과 표준편차가 1이 되도록 변환

In [139]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

In [141]:
x = np.arange(10)
# outlier 추가
x[9] = 1000
x.mean(), x.std()

(103.6, 298.8100399919654)

In [143]:
scaled = standard_scaler.fit_transform(x.reshape(-1, 1))
scaled

array([[-0.34670856],
       [-0.34336196],
       [-0.34001535],
       [-0.33666874],
       [-0.33332213],
       [-0.32997553],
       [-0.32662892],
       [-0.32328231],
       [-0.3199357 ],
       [ 2.9998992 ]])

In [144]:
x.mean(), x.std()

(103.6, 298.8100399919654)

In [145]:
scaled.mean(), scaled.std()

(4.4408920985006264e-17, 1.0)

In [146]:
round(scaled.mean(), 2), scaled.std()

(0.0, 1.0)